print("Welcome to INEC official platform, please enter your details: ")
username = input ("what is your name: \n")
age = input ("How old are you: \n")
stateoforigin = input("where are you from:\n")
occupation = input("what is your occupation: \n")
preferedCandidate = input ("Enter your candidate:\n")
print("\nMy name is", "\033[37m", username)
print("\nI am", "\033[36m",age)
print("\nI am from", "\033[32m", stateoforigin)
print("\n I am a", "\033[31m", occupation)
print("\nMy prefered candidate is", "\033[35m", preferedCandidate)
